[package]
name = "vizion"
version = "0.1.0"
authors = ["John Wennstr√∏m <john.wennstrom@protonmail.com>"]
edition = "2018"

[workspace]

[dependencies]
unskew = {path = "libs/unskew"}
face_detection = {path = "libs/face_detection"}
clap = "2.33.0"
